# Generated by Django 4.2.4 on 2023-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
