# Generated by Django 4.2.4 on 2023-09-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0012_alter_webfullinfo_port_alter_webfullinfo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainsdns',
            name='a_record',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='aaaa_record',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='cname',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='host',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='internal_ips_record',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='mx_record',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='ns_record',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='resolver',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subdomainsdns',
            name='soa_record',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
