# Generated by Django 4.2.4 on 2023-08-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_remove_client_on_trial_remove_client_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
