# Generated by Django 4.2.4 on 2023-08-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
