# Generated by Django 4.2.4 on 2023-09-03 10:30

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_rename_client_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain_url',
            field=models.CharField(default='localhost', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name]),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
